// Dependency Injection Type Identifiers

export const TYPES = {
    // Infrastructure
    Logger: Symbol.for('Logger'),

    TransactionManager: Symbol.for('TransactionManager'),

    // Repositories
    UserRepository: Symbol.for('UserRepository'),
    ServerRepository: Symbol.for('ServerRepository'),
    MessageRepository: Symbol.for('MessageRepository'),
    BanRepository: Symbol.for('BanRepository'),
    MuteRepository: Symbol.for('MuteRepository'),
    ServerMemberRepository: Symbol.for('ServerMemberRepository'),
    RoleRepository: Symbol.for('RoleRepository'),
    DmUnreadRepository: Symbol.for('DmUnreadRepository'),
    WarningRepository: Symbol.for('WarningRepository'),
    FriendshipRepository: Symbol.for('FriendshipRepository'),
    EmojiRepository: Symbol.for('EmojiRepository'),
    StickerRepository: Symbol.for('StickerRepository'),
    WebhookRepository: Symbol.for('WebhookRepository'),
    ChannelRepository: Symbol.for('ChannelRepository'),
    CategoryRepository: Symbol.for('CategoryRepository'),
    AuditLogRepository: Symbol.for('AuditLogRepository'),
    InviteRepository: Symbol.for('InviteRepository'),
    VanityLinkRepository: Symbol.for('VanityLinkRepository'),
    ServerBanRepository: Symbol.for('ServerBanRepository'),
    ServerChannelReadRepository: Symbol.for('ServerChannelReadRepository'),
    ChannelReadRepository: Symbol.for('ChannelReadRepository'),
    PingRepository: Symbol.for('PingRepository'),
    ReactionRepository: Symbol.for('ReactionRepository'),
    ExportJobRepository: Symbol.for('ExportJobRepository'),
    BlockRepository: Symbol.for('BlockRepository'),
    AdminNoteRepository: Symbol.for('AdminNoteRepository'),
    SlashCommandRepository: Symbol.for('SlashCommandRepository'),
    SessionRepository: Symbol.for('SessionRepository'),
    ExportService: Symbol.for('ExportService'),

    AuthService: Symbol.for('AuthService'),
    PermissionService: Symbol.for('PermissionService'),
    WebPushService: Symbol.for('WebPushService'),
    KlipyService: Symbol.for('KlipyService'),
    GifTagService: Symbol.for('GifTagService'),

    PingService: Symbol.for('PingService'),
    MailService: Symbol.for('MailService'),
    MailConfig: Symbol.for('MailConfig'),
    MetricsService: Symbol.for('MetricsService'),
    PasswordResetRepository: Symbol.for('PasswordResetRepository'),
    ServerAuditLogService: Symbol.for('ServerAuditLogService'),
    RedisService: Symbol.for('RedisService'),
    ImageDeliveryService: Symbol.for('ImageDeliveryService'),
    ScraperService: Symbol.for('ScraperService'),
    EmbedService: Symbol.for('EmbedService'),
    ServerVerificationService: Symbol.for('ServerVerificationService'),
    ServerDiscoveryService: Symbol.for('ServerDiscoveryService'),
    MessageSearchService: Symbol.for('MessageSearchService'),
    ChannelService: Symbol.for('ChannelService'),
    ElasticsearchConfig: Symbol.for('ElasticsearchConfig'),

    // Application
    GeoIpService: Symbol.for('GeoIpService'),
    VpnDetectionService: Symbol.for('VpnDetectionService'),

    ExpressApp: Symbol.for('ExpressApp'),
    WsServer: Symbol.for('WsServer'),
    WsDispatcher: Symbol.for('WsDispatcher'),
    WsController: Symbol.for('WsController'),
    PresenceController: Symbol.for('PresenceController'),
    RegistrationInviteService: Symbol.for('RegistrationInviteService'),
};
